name: Publish GitHub.com/packages

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    name: Update package
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
        
      - name: Building
        run: |
          dotnet build MathCore.AI -c Release
          dotnet build Tests/MathCore.AI.Tests -c Release
        
      - name: Testing
        run: dotnet test Tests/MathCore.AI.Tests -c Release --no-build
        
      - name: Packing
        run: dotnet pack MathCore.AI -c Release --no-build        
      
      - name: Push package
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate -s https://nuget.pkg.github.com/Infarh/index.json -k ${{secrets.GITHUB_TOKEN}}
